POST http://localhost:4000/movie/6647a39e7e44195b1eeaab03
Content-Type: application/json

{
  "name": "Mi película con múltiples géneros 2",
  "image": "urlexample",
  "score": 9,
  "synopsis": "Descripción de la película",
  "genresIDs": [
    "6647a3cf7e44195b1eeaab05"
  ]
}